--
-- PostgreSQL database dump
--

-- Dumped from database version 16.11 (Debian 16.11-1.pgdg13+1)
-- Dumped by pg_dump version 16.1

-- Started on 2025-12-03 21:53:18

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 3470 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 225 (class 1259 OID 16429)
-- Name: Addresses; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public."Addresses" (
    "Id" integer NOT NULL,
    "UserId" integer NOT NULL,
    "CityId" integer NOT NULL,
    "Street" character varying(150) NOT NULL
);


ALTER TABLE public."Addresses" OWNER TO "user";

--
-- TOC entry 224 (class 1259 OID 16428)
-- Name: Addresses_Id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public."Addresses" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Addresses_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16418)
-- Name: Cities; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public."Cities" (
    "Id" integer NOT NULL,
    "DepartmentId" integer NOT NULL,
    "Name" character varying(100) NOT NULL
);


ALTER TABLE public."Cities" OWNER TO "user";

--
-- TOC entry 222 (class 1259 OID 16417)
-- Name: Cities_Id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public."Cities" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Cities_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 16395)
-- Name: Countries; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public."Countries" (
    "Id" integer NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Code" character varying(5) NOT NULL
);


ALTER TABLE public."Countries" OWNER TO "user";

--
-- TOC entry 216 (class 1259 OID 16394)
-- Name: Countries_Id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public."Countries" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Countries_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16407)
-- Name: Departments; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public."Departments" (
    "Id" integer NOT NULL,
    "CountryId" integer NOT NULL,
    "Name" character varying(100) NOT NULL
);


ALTER TABLE public."Departments" OWNER TO "user";

--
-- TOC entry 220 (class 1259 OID 16406)
-- Name: Departments_Id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public."Departments" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Departments_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16401)
-- Name: Users; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public."Users" (
    "Id" integer NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Phone" character varying(20) NOT NULL
);


ALTER TABLE public."Users" OWNER TO "user";

--
-- TOC entry 218 (class 1259 OID 16400)
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 16389)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO "user";

--
-- TOC entry 3464 (class 0 OID 16429)
-- Dependencies: 225
-- Data for Name: Addresses; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public."Addresses" ("Id", "UserId", "CityId", "Street") FROM stdin;
\.


--
-- TOC entry 3462 (class 0 OID 16418)
-- Dependencies: 223
-- Data for Name: Cities; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public."Cities" ("Id", "DepartmentId", "Name") FROM stdin;
1	1	Medellín
2	1	Envigado
3	1	Marinilla
4	2	Bogotá
5	2	Cajicá
6	2	Chía
7	3	Cali
8	3	Palmira
9	3	Buenaventura
\.


--
-- TOC entry 3456 (class 0 OID 16395)
-- Dependencies: 217
-- Data for Name: Countries; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public."Countries" ("Id", "Name", "Code") FROM stdin;
1	Colombia	CO
\.


--
-- TOC entry 3460 (class 0 OID 16407)
-- Dependencies: 221
-- Data for Name: Departments; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public."Departments" ("Id", "CountryId", "Name") FROM stdin;
1	1	Antioquia
2	1	Cundinamarca
3	1	Valle del Cauca
\.


--
-- TOC entry 3458 (class 0 OID 16401)
-- Dependencies: 219
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public."Users" ("Id", "Name", "Phone") FROM stdin;
\.


--
-- TOC entry 3454 (class 0 OID 16389)
-- Dependencies: 215
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20251204025122_InitialCreate	8.0.0
\.


--
-- TOC entry 3471 (class 0 OID 0)
-- Dependencies: 224
-- Name: Addresses_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public."Addresses_Id_seq"', 1, false);


--
-- TOC entry 3472 (class 0 OID 0)
-- Dependencies: 222
-- Name: Cities_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public."Cities_Id_seq"', 10, false);


--
-- TOC entry 3473 (class 0 OID 0)
-- Dependencies: 216
-- Name: Countries_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public."Countries_Id_seq"', 2, false);


--
-- TOC entry 3474 (class 0 OID 0)
-- Dependencies: 220
-- Name: Departments_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public."Departments_Id_seq"', 4, false);


--
-- TOC entry 3475 (class 0 OID 0)
-- Dependencies: 218
-- Name: Users_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public."Users_Id_seq"', 1, false);


--
-- TOC entry 3306 (class 2606 OID 16433)
-- Name: Addresses PK_Addresses; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public."Addresses"
    ADD CONSTRAINT "PK_Addresses" PRIMARY KEY ("Id");


--
-- TOC entry 3302 (class 2606 OID 16422)
-- Name: Cities PK_Cities; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public."Cities"
    ADD CONSTRAINT "PK_Cities" PRIMARY KEY ("Id");


--
-- TOC entry 3294 (class 2606 OID 16399)
-- Name: Countries PK_Countries; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public."Countries"
    ADD CONSTRAINT "PK_Countries" PRIMARY KEY ("Id");


--
-- TOC entry 3299 (class 2606 OID 16411)
-- Name: Departments PK_Departments; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public."Departments"
    ADD CONSTRAINT "PK_Departments" PRIMARY KEY ("Id");


--
-- TOC entry 3296 (class 2606 OID 16405)
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- TOC entry 3292 (class 2606 OID 16393)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 3303 (class 1259 OID 16444)
-- Name: IX_Addresses_CityId; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX "IX_Addresses_CityId" ON public."Addresses" USING btree ("CityId");


--
-- TOC entry 3304 (class 1259 OID 16445)
-- Name: IX_Addresses_UserId; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX "IX_Addresses_UserId" ON public."Addresses" USING btree ("UserId");


--
-- TOC entry 3300 (class 1259 OID 16446)
-- Name: IX_Cities_DepartmentId; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX "IX_Cities_DepartmentId" ON public."Cities" USING btree ("DepartmentId");


--
-- TOC entry 3297 (class 1259 OID 16447)
-- Name: IX_Departments_CountryId; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX "IX_Departments_CountryId" ON public."Departments" USING btree ("CountryId");


--
-- TOC entry 3309 (class 2606 OID 16434)
-- Name: Addresses FK_Addresses_Cities_CityId; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public."Addresses"
    ADD CONSTRAINT "FK_Addresses_Cities_CityId" FOREIGN KEY ("CityId") REFERENCES public."Cities"("Id") ON DELETE CASCADE;


--
-- TOC entry 3310 (class 2606 OID 16439)
-- Name: Addresses FK_Addresses_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public."Addresses"
    ADD CONSTRAINT "FK_Addresses_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- TOC entry 3308 (class 2606 OID 16423)
-- Name: Cities FK_Cities_Departments_DepartmentId; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public."Cities"
    ADD CONSTRAINT "FK_Cities_Departments_DepartmentId" FOREIGN KEY ("DepartmentId") REFERENCES public."Departments"("Id") ON DELETE CASCADE;


--
-- TOC entry 3307 (class 2606 OID 16412)
-- Name: Departments FK_Departments_Countries_CountryId; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public."Departments"
    ADD CONSTRAINT "FK_Departments_Countries_CountryId" FOREIGN KEY ("CountryId") REFERENCES public."Countries"("Id") ON DELETE CASCADE;


-- Completed on 2025-12-03 21:53:18

--
-- PostgreSQL database dump complete
--

